import React, { Component } from 'react';
import imag from './images/crop1.jpg';
import './App.css';

class App extends Component {
  render() {
    return (
      <div className="App">
          <img src={imag} className="App-logo" alt="crop1" width="1600" height="158" />

          <div align="center" style="margin:0 auto; max-width:700px;">
          <table width="100%" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td><!--[if (gte mso 9)|(IE)]>
                                <table width="700" align="center" cellpadding="0" cellspacing="0" border="0" class="fix-width-table" style="text-align: center;margin: 0 auto;">
                                  <tr>
                                    <td>
                              <![endif]--></td>
            </tr>
            <tr>
            	<td width="100%" align="center" valign="top"><span style="font-family:Arial, Helvetica, sans-serif; font-size:13px; color:#a2a7ab; line-height:20px;"><a href="[[autogeneratedpage]]" target="_blank" style="color:#000000;">View this email in your browser.</a></span></td>
            </tr>
            <tr>
                <td align="center" valign="top"><a href="http://www.techweek.ro/" target="_blank"><img src="http://www.whiteimage.biz/clients/inworld/2017/no18/images/header2.jpg" alt="" width="100%" border="0" style="display:block;" /></a></td>
              </tr>
            <tr>
                <td align="center" valign="top"><a href="http://www.techweek.ro/" target="_blank"><img src="http://www.whiteimage.biz/clients/inworld/2017/no21/images/head2.jpg" alt="Only 3 weeks left until Business Summits" width="100%" border="0" style="display:block;" /></a></td>
              </tr>
                <tr>
                  <td align="center" valign="top" height="20">&nbsp;</td>
                </tr>
                <tr>
                  <td align="center" valign="top"><table width="100%" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td width="32%">&nbsp;</td>
              <td width="37%" align="center" valign="top"><a href="http://techweek.ro/register/" target="_blank"><img src="http://www.whiteimage.biz/clients/inworld/2017/no18/images/btn1.jpg" alt="Register now" width="100%" border="0" style="display:block; max-width:259px;" /></a></td>
              <td width="31%">&nbsp;</td>
            </tr>
          </table></td>
                </tr>
                <tr>
                  <td align="center" valign="top" height="26">&nbsp;</td>
                </tr>
                <tr>
                  <td align="center" valign="top"><table width="89%" border="0" cellspacing="0" cellpadding="0" bgcolor="#048875">
            <tr>
              <td height="13" bgcolor="#048875"></td>
            </tr>
            <tr>
              <td align="center" valign="top" bgcolor="#048875"><span style="font-family:Arial, Helvetica, sans-serif; font-size:20px; text-align:center; line-height:28px; color:#ffffff">Here you can find the last confirmed speakers:</span></td>
            </tr>
            <tr>
              <td height="13" bgcolor="#048875"></td>
            </tr>
          </table>
          </td>
                </tr>
                <tr>
                  <td align="center" valign="top" height="26">&nbsp;</td>
                </tr>
                <tr>
                	<td align="center" valign="top"><table width="92%" border="0" cellspacing="0" cellpadding="0" style="max-width:644px;">
                    <tr>
                      <td><!--[if (gte mso 9)|(IE)]>
                                <table width="644" align="center" cellpadding="0" cellspacing="0" border="0" class="fix-width-table" style="text-align: center;margin: 0 auto;">
                                  <tr>
                                    <td>
                              <![endif]--></td>
                    </tr>
                    <tr>
                      <td align="center" valign="top"><table width="100%" border="0" cellspacing="0" cellpadding="0" style="max-width:644px;">
                          <tr>
                            <td dir="ltl" class="two-column" style="padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;text-align:center;font-size:0;" >
                            <!--[if (gte mso 9)|(IE)]>
                  			<table width="100%" border="0" cellspacing="0" cellpadding="0" style="border-spacing:0;" >
                  				<tr>
                  					<td width="214" valign="top" style="padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;" >
                  		  <![endif]-->
                              <div class="column" style="width:100%; max-width:214px; display:inline-block; vertical-align:top;" >
                                <table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" style="border-spacing:0;" >
                                  <tr>
                                    <td valign="bottom" class="inner" style="padding-top:0; padding-bottom:0; padding-right:0; padding-left:0;" ><table align="center" border="0" cellspacing="0" cellpadding="0" style="border-spacing:0; width:100%;" >
                                        <tr>
                                          <td dir="ltl" style="padding-top:10px; padding-bottom:0; padding-right:0; padding-left:0;" valign="top"><table width="214" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td align="center" valign="top"><table width="194" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td height="8" bgcolor="#f0e119"></td>
            </tr>
            <tr>
              <td align="center" valign="top" bgcolor="#f0e119"><table width="184" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td width="36" align="left" valign="top"><span style="font-family:Arial, Helvetica, sans-serif; font-size:17px; text-align:left; line-height:22px; color:#ffffff">23rd <br />
          May</span></td>
              <td width="53" align="left" valign="top">&nbsp;</td>
              <td width="95" align="right" valign="top"><span style="font-family:Arial, Helvetica, sans-serif; font-size:15px; text-align:right; line-height:22px; color:#ffffff">INNOVATION SUMMIT</span></td>
            </tr>
          </table>
          </td>
            </tr>
            <tr>
              <td height="8" bgcolor="#f0e119"></td>
            </tr>
            <tr>
              <td align="center" valign="top"><img src="http://www.whiteimage.biz/clients/inworld/2017/no18/images/img1.jpg" alt="" width="194" border="0" style="display:block;" /></td>
            </tr>
            <tr>
              <td height="26" align="center" valign="middle" bgcolor="#3f3f3f"><span style="font-family:Arial, Helvetica, sans-serif; font-size:15px; text-align:right; line-height:28px; color:#ffffff">GA&Euml;L LANGEVIN</span></td>
            </tr>
            <tr>
              <td height="6" bgcolor="#606060"></td>
            </tr>
            <tr>
              <td align="center" valign="top" bgcolor="#606060"><span style="font-family:Arial, Helvetica, sans-serif; font-size:16px; text-align:center; line-height:20px; color:#ffffff">Designer, Sculptor <br />
          & Creator</span></td>
            </tr>
            <tr>
              <td height="6" bgcolor="#606060"></td>
            </tr>
          </table></td>
            </tr>
          </table>

          </td>
                                        </tr>
                                      </table></td>
                                  </tr>
                                </table>
                              </div>
                              <!--[if (gte mso 9)|(IE)]>
                  				</td>
                  					<td width="214" valign="top" style="padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;" >
                  				<![endif]-->
                              <div class="column" style="width:100%; max-width:214px;display:inline-block; vertical-align:top;" >
                                <table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" style="border-spacing:0;" >
                                  <tr>
                                    <td valign="bottom" class="inner" style="padding-top:0; padding-bottom:0; padding-right:0; padding-left:0;" ><table align="center" border="0" cellspacing="0" cellpadding="0" style="border-spacing:0; width:100%;" >
                                        <tr>
                                          <td dir="ltl" style="padding-top:10px; padding-bottom:0; padding-right:0; padding-left:0;" valign="top"><table width="214" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td align="center" valign="top"><table width="194" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td height="8" bgcolor="#fcbb15"></td>
            </tr>
            <tr>
              <td align="center" valign="top" bgcolor="#fcbb15"><table width="184" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td width="36" align="left" valign="top"><span style="font-family:Arial, Helvetica, sans-serif; font-size:17px; text-align:left; line-height:22px; color:#ffffff">24th <br />
          May</span></td>
              <td width="40" align="left" valign="top">&nbsp;</td>
              <td width="108" align="right" valign="top"><span style="font-family:Arial, Helvetica, sans-serif; font-size:15px; text-align:right; line-height:22px; color:#ffffff">HR MASTERS SUMMIT</span></td>
            </tr>
          </table>
          </td>
            </tr>
            <tr>
              <td height="8" bgcolor="#fcbb15"></td>
            </tr>
            <tr>
              <td align="center" valign="top"><img src="http://www.whiteimage.biz/clients/inworld/2017/no18/images/img2.jpg" alt="" width="194" border="0" style="display:block;" /></td>
            </tr>
            <tr>
              <td height="26" align="center" valign="middle" bgcolor="#3f3f3f"><span style="font-family:Arial, Helvetica, sans-serif; font-size:15px; text-align:right; line-height:28px; color:#ffffff">DR. REZA MOUSSAVIAN</span></td>
            </tr>
            <tr>
              <td height="6" bgcolor="#606060"></td>
            </tr>
            <tr>
              <td align="center" valign="top" bgcolor="#606060"><span style="font-family:Arial, Helvetica, sans-serif; font-size:16px; text-align:center; line-height:20px; color:#ffffff">SVP HR Digital <br />
          & Innovation @ Telekom</span></td>
            </tr>
            <tr>
              <td height="6" bgcolor="#606060"></td>
            </tr>
          </table></td>
            </tr>
          </table></td>
                                        </tr>
                                      </table></td>
                                  </tr>
                                </table>
                              </div>
                              <!--[if (gte mso 9)|(IE)]>
                  				</td>

                  					<td width="214" valign="top" style="padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;" >
                  			<![endif]-->
                              <div class="column" style="width:100%; max-width:214px; display:inline-block; vertical-align:top;" >
                                <table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" style="border-spacing:0;" >
                                  <tr>
                                    <td valign="bottom" class="inner" style="padding-top:0; padding-bottom:0; padding-right:0; padding-left:0;" ><table align="center" border="0" cellspacing="0" cellpadding="0" style="border-spacing:0; width:100%;" >
                                        <tr>
                                          <td dir="ltl" style="padding-top:10px; padding-bottom:0; padding-right:0; padding-left:0;"  valign="top"><table width="214" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td align="center" valign="top"><table width="194" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td height="8" bgcolor="#12cc5e"></td>
            </tr>
            <tr>
              <td align="center" valign="top" bgcolor="#12cc5e"><table width="184" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td width="36" align="left" valign="top"><span style="font-family:Arial, Helvetica, sans-serif; font-size:17px; text-align:left; line-height:22px; color:#ffffff">25th <br />
          May</span></td>
              <td width="20" align="left" valign="top">&nbsp;</td>
              <td width="128" align="right" valign="top"><span style="font-family:Arial, Helvetica, sans-serif; font-size:15px; text-align:right; line-height:22px; color:#ffffff">SALES LEADERS SUMMIT</span></td>
            </tr>
          </table>
          </td>
            </tr>
            <tr>
              <td height="8" bgcolor="#12cc5e"></td>
            </tr>
            <tr>
              <td align="center" valign="top"><img src="http://www.whiteimage.biz/clients/inworld/2017/no18/images/img3.jpg" alt="" width="194" border="0" style="display:block;" /></td>
            </tr>
            <tr>
              <td height="26" align="center" valign="middle" bgcolor="#3f3f3f"><span style="font-family:Arial, Helvetica, sans-serif; font-size:15px; text-align:right; line-height:28px; color:#ffffff">SPENCER WALDRON</span></td>
            </tr>
            <tr>
              <td height="6" bgcolor="#606060"></td>
            </tr>
            <tr>
              <td align="center" valign="top" bgcolor="#606060"><span style="font-family:Arial, Helvetica, sans-serif; font-size:16px; text-align:center; line-height:20px; color:#ffffff">Regional European <br />
          Director @ Prezi</span></td>
            </tr>
            <tr>
              <td height="6" bgcolor="#606060"></td>
            </tr>
          </table></td>
            </tr>
          </table></td>
                                        </tr>
                                      </table></td>
                                  </tr>
                                </table>
                              </div>
                              <!--[if (gte mso 9)|(IE)]>
                  </td>
                  </tr>
                  </table>
                  <![endif]--></td>
                          </tr>
                        </table></td>
                    </tr>
                    <tr>
                      <td><!--[if (gte mso 9)|(IE)]>
                                      </td>
                                   </tr>
                                </table>
                              <![endif]--></td>
                    </tr>
                  </table></td>
              </tr>
                <tr>
                  <td align="center" valign="top" height="25">&nbsp;</td>
                </tr>
                <tr>
                	<td align="center" valign="top"><table width="92%" border="0" cellspacing="0" cellpadding="0" style="max-width:644px;">
                    <tr>
                      <td><!--[if (gte mso 9)|(IE)]>
                                <table width="644" align="center" cellpadding="0" cellspacing="0" border="0" class="fix-width-table" style="text-align: center;margin: 0 auto;">
                                  <tr>
                                    <td>
                              <![endif]--></td>
                    </tr>
                    <tr>
                      <td align="center" valign="top"><table width="100%" border="0" cellspacing="0" cellpadding="0" style="max-width:644px;">
                          <tr>
                            <td dir="ltl" class="two-column" style="padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;text-align:center;font-size:0;" >
                            <!--[if (gte mso 9)|(IE)]>
                  			<table width="100%" border="0" cellspacing="0" cellpadding="0" style="border-spacing:0;" >
                  				<tr>
                  					<td width="214" valign="top" style="padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;" >
                  		  <![endif]-->
                              <div class="column" style="width:100%; max-width:214px; display:inline-block; vertical-align:top;" >
                                <table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" style="border-spacing:0;" >
                                  <tr>
                                    <td valign="bottom" class="inner" style="padding-top:0; padding-bottom:0; padding-right:0; padding-left:0;" ><table align="center" border="0" cellspacing="0" cellpadding="0" style="border-spacing:0; width:100%;" >
                                        <tr>
                                          <td dir="ltl" style="padding-top:10px; padding-bottom:0; padding-right:0; padding-left:0;" valign="top"><table width="214" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td align="center" valign="top"><table width="194" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td height="8" bgcolor="#3b80b9"></td>
            </tr>
            <tr>
              <td align="center" valign="top" bgcolor="#3b80b9"><table width="184" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td width="36" align="left" valign="top"><span style="font-family:Arial, Helvetica, sans-serif; font-size:17px; text-align:left; line-height:22px; color:#ffffff">25th <br />
          May</span></td>
              <td width="25" align="left" valign="top">&nbsp;</td>
              <td width="123" align="right" valign="top"><span style="font-family:Arial, Helvetica, sans-serif; font-size:15px; text-align:right; line-height:22px; color:#ffffff">SALES LEADERS
          SUMMIT</span></td>
            </tr>
          </table>
          </td>
            </tr>
            <tr>
              <td height="8" bgcolor="#3b80b9"></td>
            </tr>
            <tr>
              <td align="center" valign="top"><img src="http://www.whiteimage.biz/clients/inworld/2017/no18/images/img4.jpg" alt="" width="194" border="0" style="display:block;" /></td>
            </tr>
            <tr>
              <td height="26" align="center" valign="middle" bgcolor="#3f3f3f"><span style="font-family:Arial, Helvetica, sans-serif; font-size:15px; text-align:right; line-height:28px; color:#ffffff">DAVID MCQUEEN</span></td>
            </tr>
            <tr>
              <td height="6" bgcolor="#606060"></td>
            </tr>
            <tr>
              <td align="center" valign="top" bgcolor="#606060"><span style="font-family:Arial, Helvetica, sans-serif; font-size:16px; text-align:center; line-height:20px; color:#ffffff">Businessman &<br />
          International speaker</span></td>
            </tr>
            <tr>
              <td height="6" bgcolor="#606060"></td>
            </tr>
          </table></td>
            </tr>
          </table>

          </td>
                                        </tr>
                                      </table></td>
                                  </tr>
                                </table>
                              </div>
                              <!--[if (gte mso 9)|(IE)]>
                  				</td>
                  					<td width="214" valign="top" style="padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;" >
                  				<![endif]-->
                              <div class="column" style="width:100%; max-width:214px;display:inline-block; vertical-align:top;" >
                                <table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" style="border-spacing:0;" >
                                  <tr>
                                    <td valign="bottom" class="inner" style="padding-top:0; padding-bottom:0; padding-right:0; padding-left:0;" ><table align="center" border="0" cellspacing="0" cellpadding="0" style="border-spacing:0; width:100%;" >
                                        <tr>
                                          <td dir="ltl" style="padding-top:10px; padding-bottom:0; padding-right:0; padding-left:0;" valign="top"><table width="214" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td align="center" valign="top"><table width="194" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td height="8" bgcolor="#e03c27"></td>
            </tr>
            <tr>
              <td align="center" valign="top" bgcolor="#e03c27"><table width="184" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td width="36" align="left" valign="top"><span style="font-family:Arial, Helvetica, sans-serif; font-size:17px; text-align:left; line-height:22px; color:#ffffff">26th <br />
          May</span></td>
              <td width="40" align="left" valign="top">&nbsp;</td>
              <td width="108" align="right" valign="top"><span style="font-family:Arial, Helvetica, sans-serif; font-size:15px; text-align:right; line-height:22px; color:#ffffff">JAVA<br />
          SUMMIT</span></td>
            </tr>
          </table>
          </td>
            </tr>
            <tr>
              <td height="8" bgcolor="#e03c27"></td>
            </tr>
            <tr>
              <td align="center" valign="top"><img src="http://www.whiteimage.biz/clients/inworld/2017/no18/images/img5.jpg" alt="" width="194" border="0" style="display:block;" /></td>
            </tr>
            <tr>
              <td height="26" align="center" valign="middle" bgcolor="#3f3f3f"><span style="font-family:Arial, Helvetica, sans-serif; font-size:15px; text-align:right; line-height:28px; color:#ffffff">AMIRA LAKHAL</span></td>
            </tr>
            <tr>
              <td height="6" bgcolor="#606060"></td>
            </tr>
            <tr>
              <td align="center" valign="top" bgcolor="#606060"><span style="font-family:Arial, Helvetica, sans-serif; font-size:16px; text-align:center; line-height:20px; color:#ffffff">Agile Java &<br />
          Java Champion</span></td>
            </tr>
            <tr>
              <td height="6" bgcolor="#606060"></td>
            </tr>
          </table></td>
            </tr>
          </table></td>
                                        </tr>
                                      </table></td>
                                  </tr>
                                </table>
                              </div>
                              <!--[if (gte mso 9)|(IE)]>
                  				</td>

                  					<td width="214" valign="top" style="padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;" >
                  			<![endif]-->
                              <div class="column" style="width:100%; max-width:214px; display:inline-block; vertical-align:top;" >
                                <table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" style="border-spacing:0;" >
                                  <tr>
                                    <td valign="bottom" class="inner" style="padding-top:0; padding-bottom:0; padding-right:0; padding-left:0;" ><table align="center" border="0" cellspacing="0" cellpadding="0" style="border-spacing:0; width:100%;" >
                                        <tr>
                                          <td dir="ltl" style="padding-top:10px; padding-bottom:0; padding-right:0; padding-left:0;"  valign="top"><table width="214" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td align="center" valign="top"><table width="194" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td height="8" bgcolor="#5d2b7c"></td>
            </tr>
            <tr>
              <td align="center" valign="top" bgcolor="#5d2b7c"><table width="184" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td width="36" align="left" valign="top"><span style="font-family:Arial, Helvetica, sans-serif; font-size:17px; text-align:left; line-height:22px; color:#ffffff">26th <br />
          May</span></td>
              <td width="20" align="left" valign="top">&nbsp;</td>
              <td width="128" align="right" valign="top"><span style="font-family:Arial, Helvetica, sans-serif; font-size:15px; text-align:right; line-height:22px; color:#ffffff">PHP<br />
          SUMMIT</span></td>
            </tr>
          </table>
          </td>
            </tr>
            <tr>
              <td height="8" bgcolor="#5d2b7c"></td>
            </tr>
            <tr>
              <td align="center" valign="top"><img src="http://www.whiteimage.biz/clients/inworld/2017/no18/images/img6.jpg" alt="" width="194" border="0" style="display:block;" /></td>
            </tr>
            <tr>
              <td height="26" align="center" valign="middle" bgcolor="#3f3f3f"><span style="font-family:Arial, Helvetica, sans-serif; font-size:15px; text-align:right; line-height:28px; color:#ffffff">JAMES TITCUMB</span></td>
            </tr>
            <tr>
              <td height="6" bgcolor="#606060"></td>
            </tr>
            <tr>
              <td align="center" valign="top" bgcolor="#606060"><span style="font-family:Arial, Helvetica, sans-serif; font-size:16px; text-align:center; line-height:20px; color:#ffffff">Freelance Consultant &<br />
          Engineer @ Roave</span></td>
            </tr>
            <tr>
              <td height="6" bgcolor="#606060"></td>
            </tr>
          </table></td>
            </tr>
          </table></td>
                                        </tr>
                                      </table></td>
                                  </tr>
                                </table>
                              </div>
                              <!--[if (gte mso 9)|(IE)]>
                  </td>
                  </tr>
                  </table>
                  <![endif]--></td>
                          </tr>
                        </table></td>
                    </tr>
                    <tr>
                      <td><!--[if (gte mso 9)|(IE)]>
                                      </td>
                                   </tr>
                                </table>
                              <![endif]--></td>
                    </tr>
                  </table></td>
              </tr>
                <tr>
                  <td align="center" valign="top" height="26">&nbsp;</td>
                </tr>
                <tr>
                  <td align="center" valign="top"><table width="100%" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td width="10%">&nbsp;</td>
              <td width="80%" align="center" valign="top"><span style="font-family:Arial, Helvetica, sans-serif; font-size:19px; line-height:30px; color:#006837;">Because immersive experiences deserve to be shared,
          we encourage group participation with extra discounts.</span></td>
              <td width="10">&nbsp;</td>
            </tr>
          </table>
          </td>
                </tr>
                <tr>
                  <td align="center" valign="top" height="26">&nbsp;</td>
                </tr>
                <tr>
                            <td align="center" valign="top"><table width="92%" border="0" cellspacing="0" cellpadding="0" style="max-width:644px;">
                                <tr>
                                  <td><!--[if (gte mso 9)|(IE)]>
                                <table width="644" align="center" cellpadding="0" cellspacing="0" border="0" class="fix-width-table" style="text-align: center;margin: 0 auto;">
                                  <tr>
                                    <td>
                              <![endif]--></td>
                                </tr>
                                <tr>
                                  <td align="center" valign="top"><table width="100%" border="0" cellspacing="0" cellpadding="0" style="max-width:644px;">
                                      <tr>
                                        <td dir="ltl" class="two-column" valign="top" style="padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;text-align:center;font-size:0;" ><!--[if (gte mso 9)|(IE)]>
                  <table width="100%" style="border-spacing:0;" border="0" cellspacing="0" cellpadding="0" >
                  <tr>
                  <td width="322" valign="top" style="padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;" >
                  <![endif]-->
                                          <div class="column" style="width:100%; max-width:322px;display:inline-block; vertical-align:top;" >
                                            <table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" style="border-spacing:0;" >
                                              <tr>
                                                <td valign="bottom" class="inner" style="padding-top:0; padding-bottom:0; padding-right:0; padding-left:0;" ><table align="center" border="0"  cellpadding="0" cellspacing="0" style="border-spacing:0; width:100%;" >
                                                    <tr>
                                                      <td dir="ltl" style="padding-top:10px; padding-bottom:0; padding-right:0; padding-left:0;" valign="top" align="center"><table width="308" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td align="center" valign="top" style="border:1px solid #c6c6c6"><table width="270" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td height="10"></td>
            </tr>
            <tr>
              <td align="center" valign="top"><span style="font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:18px; color:#000000;"><strong>2 DAYS CONFERENCE PASS</strong><br />
          For a 2 days conference pass, please send us
          an email at <a href="mailto:contact@tech.week.ro" target="_blank" style="color:#000000; text-decoration:none;">contact@tech.week.ro</a></span></td>
            </tr>
            <tr>
              <td height="10"></td>
            </tr>
          </table>
          </td>
            </tr>
          </table>
          </td>
                                                    </tr>
                                                  </table></td>
                                              </tr>
                                            </table>
                                          </div>
                                          <!--[if (gte mso 9)|(IE)]>
                  </td><td width="322" valign="top" style="padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;" >
                  <![endif]-->
                                          <div class="column" style="width:100%; max-width:322px;display:inline-block; vertical-align:top;" >
                                            <table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" style="border-spacing:0;" >
                                              <tr>
                                                <td valign="bottom" class="inner" style="padding-top:0; padding-bottom:0; padding-right:0; padding-left:0;" ><table align="center" border="0"  cellpadding="0" cellspacing="0" style="border-spacing:0; width:100%;" >
                                                    <tr>
                                                      <td dir="ltl" style="padding-top:10px; padding-bottom:0; padding-right:0; padding-left:0;" valign="top" align="center"><table width="308" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td align="center" valign="top" style="border:1px solid #c6c6c6"><table width="270" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td height="10"></td>
            </tr>
            <tr>
              <td align="center" valign="top"><span style="font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:18px; color:#000000;"><strong>GROUP DISCOUNT 3-5</strong><br />
          5% discount for a group of 3 to 5<br />
          participants</span></td>
            </tr>
            <tr>
              <td height="10"></td>
            </tr>
          </table>
          </td>
            </tr>
          </table></td>
                                                    </tr>
                                                  </table></td>
                                              </tr>
                                            </table>
                                          </div>
                                          <!--[if (gte mso 9)|(IE)]>
                  </td>
                  </tr>
                  </table>
                  <![endif]--></td>
                                      </tr>
                                    </table></td>
                                </tr>
                                <tr>
                                  <td><!--[if (gte mso 9)|(IE)]>
                                      </td>
                                   </tr>
                                </table>
                              <![endif]--></td>
                                </tr>
                              </table></td>
                </tr>
                <tr>
                  <td align="center" valign="top" height="10"></td>
                </tr>
                <tr>
                            <td align="center" valign="top"><table width="92%" border="0" cellspacing="0" cellpadding="0" style="max-width:644px;">
                                <tr>
                                  <td><!--[if (gte mso 9)|(IE)]>
                                <table width="644" align="center" cellpadding="0" cellspacing="0" border="0" class="fix-width-table" style="text-align: center;margin: 0 auto;">
                                  <tr>
                                    <td>
                              <![endif]--></td>
                                </tr>
                                <tr>
                                  <td align="center" valign="top"><table width="100%" border="0" cellspacing="0" cellpadding="0" style="max-width:644px;">
                                      <tr>
                                        <td dir="ltl" class="two-column" valign="top" style="padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;text-align:center;font-size:0;" ><!--[if (gte mso 9)|(IE)]>
                  <table width="100%" style="border-spacing:0;" border="0" cellspacing="0" cellpadding="0" >
                  <tr>
                  <td width="322" valign="top" style="padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;" >
                  <![endif]-->
                                          <div class="column" style="width:100%; max-width:322px;display:inline-block; vertical-align:top;" >
                                            <table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" style="border-spacing:0;" >
                                              <tr>
                                                <td valign="bottom" class="inner" style="padding-top:0; padding-bottom:10px; padding-right:0; padding-left:0;" ><table align="center" border="0"  cellpadding="0" cellspacing="0" style="border-spacing:0; width:100%;" >
                                                    <tr>
                                                      <td dir="ltl" style="padding-top:0; padding-bottom:0; padding-right:0; padding-left:0;" valign="top" align="center"><table width="308" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td align="center" valign="top" style="border:1px solid #c6c6c6"><table width="270" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td height="10"></td>
            </tr>
            <tr>
              <td align="center" valign="top"><span style="font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:18px; color:#000000;"><strong>GROUP DISCOUNT 6+</strong><br />
          10% discount for a group of more than 6<br />
          participants</span></td>
            </tr>
            <tr>
              <td height="10"></td>
            </tr>
          </table>
          </td>
            </tr>
          </table>
          </td>
                                                    </tr>
                                                  </table></td>
                                              </tr>
                                            </table>
                                          </div>
                                          <!--[if (gte mso 9)|(IE)]>
                  </td><td width="322" valign="top" style="padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;" >
                  <![endif]-->
                                          <div class="column" style="width:100%; max-width:322px;display:inline-block; vertical-align:top;" >
                                            <table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" style="border-spacing:0;" >
                                              <tr>
                                                <td valign="bottom" class="inner" style="padding-top:0; padding-bottom:0; padding-right:0; padding-left:0;" ><table align="center" border="0"  cellpadding="0" cellspacing="0" style="border-spacing:0; width:100%;" >
                                                    <tr>
                                                      <td dir="ltl" style="padding-top:0; padding-bottom:0; padding-right:0; padding-left:0;" valign="top" align="center"><table width="308" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td align="center" valign="top" style="border:1px solid #c6c6c6"><table width="280" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td height="10"></td>
            </tr>
            <tr>
              <td align="center" valign="top"><span style="font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:18px; color:#000000;"><strong>VIP PASS</strong><br />
          Ask for a VIP PASS and get access to all <br />the
          summits and to the Speakers dinner</span></td>
            </tr>
            <tr>
              <td height="10"></td>
            </tr>
          </table>
          </td>
            </tr>
          </table></td>
                                                    </tr>
                                                  </table></td>
                                              </tr>
                                            </table>
                                          </div>
                                          <!--[if (gte mso 9)|(IE)]>
                  </td>
                  </tr>
                  </table>
                  <![endif]--></td>
                                      </tr>
                                    </table></td>
                                </tr>
                                <tr>
                                  <td><!--[if (gte mso 9)|(IE)]>
                                      </td>
                                   </tr>
                                </table>
                              <![endif]--></td>
                                </tr>
                              </table></td>
                </tr>
                <tr>
                  <td align="center" valign="top" height="15"></td>
                </tr>
                <tr>
                  <td align="center" valign="top"><table width="100%" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td width="30%">&nbsp;</td>
              <td width="40%" align="center" valign="top"><a href="http://techweek.ro/register/" target="_blank"><img src="http://www.whiteimage.biz/clients/inworld/2017/no18/images/btn2.jpg" alt="Register now" width="100%" border="0" style="display:block; max-width:280px;" /></a></td>
              <td width="30%">&nbsp;</td>
            </tr>
          </table></td>
                </tr>
              <tr>
                  <td>&nbsp;</td>
              </tr>
              <tr>
                  <td align="center" valign="top" bgcolor="#53b7c8"><table width="100%" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td height="10"></td>
            </tr>
            <tr>
              <td align="center" valign="top"><span style="font-family:Arial, Helvetica, sans-serif; font-size:20px; text-align:center; line-height:28px; color:#ffffff">Meet out <strong>tech supporters</strong></span></td>
            </tr>
            <tr>
              <td height="10"></td>
            </tr>
          </table>
          </td>
              </tr>
              <tr>
                <td height="6"></td>
              </tr>
              <tr>
                <td align="center" valign="top"><img src="http://www.whiteimage.biz/clients/inworld/2017/no18/images/sigle1.jpg" alt="" width="100%" border="0" style="display:block;" /></td>
              </tr>
              <tr>
                <td align="center" valign="top"><img src="http://www.whiteimage.biz/clients/inworld/2017/no18/images/sigle2_1.jpg" alt="" width="100%" border="0" style="display:block;" /></td>
              </tr>
              <tr>
                <td align="center" valign="top"><img src="http://www.whiteimage.biz/clients/inworld/2017/no18/images/sigle3.jpg" alt="" width="100%" border="0" style="display:block;" /></td>
              </tr>
              <tr>
              <td height="6"></td>
            </tr>
            <tr>
              <td align="center" valign="top" bgcolor="#53b9ca"><table width="100%" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td width="10%">&nbsp;</td>
              <td width="80%">&nbsp;</td>
              <td width="10%">&nbsp;</td>
            </tr>
            <tr>
              <td>&nbsp;</td>
              <td align="left" valign="top"><table width="100%" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td width="85%" align="left" style="background-image:url(http://www.whiteimage.biz/clients/inworld/2017/no04/images/img_footer.jpg); background-color:#53b9ca; padding-right:3px;"><span style="font-family:Arial, Helvetica, sans-serif; font-size:17px; line-height:30px; color:#ffffff"><a href="http://techweek.ro/" target="_blank" style="color:#ffffff; text-decoration:none;">www.techweek.ro</a><br />
                  <a href="mailto:contact@techweek.ro" target="_blank" style="color:#ffffff; text-decoration:none;">contact@techweek.ro</a><br />
          0733 062 591</span></td>
              <td width="15%" align="center" valign="top"><table width="100%" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td width="50%" align="right" valign="top"><a href="https://www.facebook.com/Btechweek/" target="_blank"><img src="http://www.whiteimage.biz/clients/inworld/2017/no04/images/fb.jpg" alt="" width="30" height="30" border="0" style="display:block;" /></a></td>
              <td width="50%" align="right" valign="top"><a href="https://www.instagram.com/btechweek/?hl=ro" target="_blank"><img src="http://www.whiteimage.biz/clients/inworld/2017/no04/images/insta.jpg" alt="" width="30" height="30" border="0" style="display:block;" /></a></td>
            </tr>
            <tr>
              <td height="15"></td>
              <td height="15"></td>
            </tr>
            <tr>
              <td width="50%" align="right" valign="top"><a href="https://twitter.com/BTechWeek" target="_blank"><img src="http://www.whiteimage.biz/clients/inworld/2017/no04/images/twitter.jpg" alt="" width="30" height="30" border="0" style="display:block;" /></a></td>
              <td width="50%" align="right" valign="top"><a href="https://www.linkedin.com/groups/8489617" target="_blank"><img src="http://www.whiteimage.biz/clients/inworld/2017/no04/images/in.jpg" alt="" width="30" height="30" border="0" style="display:block;" /></a></td>
            </tr>
          </table></td>
            </tr>
          </table></td>
              <td>&nbsp;</td>
            </tr>
            <tr>
              <td height="10"></td>
              <td style="border-top:1px solid #ffffff;" height="10"></td>
              <td height="10"></td>
            </tr>
            <tr>
              <td>&nbsp;</td>
              <td align="left" valign="top"><span style="font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:18px; color:#ffffff">&copy; &nbsp; Universum Events 2017</span></td>
              <td>&nbsp;</td>
            </tr>
            <tr>
              <td>&nbsp;</td>
              <td>&nbsp;</td>
              <td>&nbsp;</td>
            </tr>
            <tr>
              <td>&nbsp;</td>
              <td align="left" valign="top"><span style="font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:18px; color:#ffffff">You are receiving this email because you registered to one of our events, subscribed to our
          newsletter or interacted directly with our team.</span></td>
              <td>&nbsp;</td>
            </tr>
            <tr>
              <td>&nbsp;</td>
              <td align="left" valign="top">&nbsp;</td>
              <td>&nbsp;</td>
            </tr>

            <tr>
              <td>&nbsp;</td>
              <td align="left" valign="top">&nbsp;</td>
              <td>&nbsp;</td>
            </tr>
          </table></td>
            </tr>
            <tr>
              <td>&nbsp;</td>
            </tr>
            <tr>
              <td><!--[if (gte mso 9)|(IE)]>
                                      </td>
                                   </tr>
                                </table>
                              <![endif]--></td>
            </tr>
          </table>

          </div>

      </div>
    );
  }
}

export default App;
